### ISSUE TITLE
Cannot read properties of undefined (reading 'ɵcmp') 

### ISSUE THREAD

**Issue by xia930425** [zzhimin/ngx-ng-zorro-formly#1]
Angular 17 引入后出现 Cannot read properties of undefined (reading 'ɵcmp') 错误

**Comment by zzhimin** [comment]
我这边用Angular17起了一个demo，你可以参考下：
https://stackblitz.com/edit/stackblitz-starters-cam7js?file=src%2Fmain.ts

好像官方还未支持Angular17，这是issues：
https://github.com/ngx-formly/ngx-formly/issues/3721
